### PR TITLE
Update .clang-format and apply clang-format

### PR DESCRIPTION
**Pull request by bernhardmgruber**
.clang-format file taken from here: https://github.com/ComputationalRadiationPhysics/contributing

### CODE REVIEW

**Review by sbastrakov — COMMENTED** [review]
Maybe it's better if this PR is split into two commits: one updates only the `.clang-format` file and is done normally. While the second adds the result of its application and is "authored" by some artificial account. I believe this is what @psychocoderHPC meant on the last alpaka meeting. For an example, see [this one](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3244#issue-419976879), also I think the command line in PR description is helpful to someone else re-doing this step later.

**Comment by bernhardmgruber** [comment]
You are absolutely right! I forgot about that! Thanks!

**Comment by psychocoderHPC** [comment]
As @sbastrakov wrote please add a separate commit for the clang file that we have a diff to the old and add the commands used to the PR description. No need to have the commands in the `commit descroption`.

**Comment by bernhardmgruber** [comment]
Here is a shell command I put in CONTRIBUTION.md half a year ago: https://github.com/alpaka-group/mallocMC/blob/dev/CONTRIBUTING.md

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
